Made changes to personalhaandbok, most notably put in info about pay …
apparatno/company pull request #27
Opened 2021-07-11 18:46 UTC by ElisabethWhiteley

…directly in that page to easily transfer this whole thing to sanity and our website.

2021-10-02 09:22 UTC, hnilsen requested changes
Hei, Elisabeth - tok sin tid dette, men jeg har gått gjennom - veldig gode endringer! Kan du gjøre små justeringer på dette så får vi det inn? :)

2021-10-02 09:22 UTC, hnilsen commented on personalhandbok.md
> +Det vil si at dersom du er på en provisjonsmodell vil du ikke få utbetalt lønn den første måneden du er ansatt, ettersom lønn beregnes av din omsetning inneværende måned.
> ettersom lønn beregnes av din omsetning inneværende måned.

Skulle det vært "ettersom lønn beregnes av din omsetning forrige måned"?

2021-10-02 09:22 UTC, hnilsen commented on personalhandbok.md
> +Forsikringen dekker blant annet... (med forbehold om at man må sjekke forsikringsbeviset for fullstendig og riktig ordlyd)
Fjerne kommentar, listen er ikke utfyllende, men linken til nettsiden gir all info man trenger.

2021-10-02 09:22 UTC, hnilsen commented on personalhandbok.md
> +Provisjonslønn blir betalt på etterskudd. Det vil si at om du begynner å arbeide for Apparat i januar på provisjonslønn, vil du få første utbetaling den 15. februar.
Kan legge til:
> Garantilønnen kobles til provisjonslønnen, og er etterskuddsvis på samme måte.

2021-10-02 09:22 UTC, hnilsen commented on personalhandbok.md
> +Bortsett fra dette fratrekket har man garantilønnen fra første måned.
Dette stemte når dere begynner, men ikke nå lenger - det ga en skjevfordeling, og garantilønnen skal følge provisjonen. Foreslår at denne setningen bare tas bort, den skal være dekket i beskrivelsen av provisjonsmodellen lenger oppe tror jeg?

2021-11-01 17:55 UTC, ElisabethWhiteley commented on personalhandbok.md
> +Forsikringen dekker blant annet... (med forbehold om at man må sjekke forsikringsbeviset for fullstendig og riktig ordlyd)
Hva mener du her? Vil du at jeg skal fjerne listen som starter fra linje 136?

2021-12-02 14:36 UTC, hnilsen commented on personalhandbok.md
> +Forsikringen dekker blant annet... (med forbehold om at man må sjekke forsikringsbeviset for fullstendig og riktig ordlyd)
Bare jeg som misforstod, please ignore

2021-12-03 16:09 UTC, hnilsen approved these changes
🎉

2021-12-03 16:10 UTC, merged